# Generated by Django 4.2.16 on 2025-10-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("app_web", "App Web"),
                    ("app_mobile", "App Mobile"),
                    ("reporting", "Reporting"),
                    ("digitalisation", "Digitalisation"),
                    ("erp", "ERP"),
                    ("ai", "AI"),
                    ("web_mobile", "Web & Mobile"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
