# Generated by Django 4.2.16 on 2025-10-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_replace_other_with_autre"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="department",
            field=models.CharField(
                choices=[
                    ("comptabilite", "Comptabilité"),
                    ("finance", "Finance"),
                    ("service_clients", "Service clients"),
                    ("risque_clients", "Risque clients"),
                    ("service_generaux", "Service généraux"),
                    ("controle_gestion", "Contrôle de gestion"),
                    ("juridique", "Juridique"),
                    ("evenementiel", "Événementiel"),
                ],
                default="comptabilite",
                max_length=20,
            ),
        ),
    ]
