# Generated by Django 4.2.16 on 2025-10-26 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_add_department_field"),
    ]

    operations = []
