# Generated by Django 4.2.7 on 2025-09-28 17:16

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_number_task_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachments',
            field=models.JSONField(blank=True, default=projects.models.default_list),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=projects.models.default_list),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, default=projects.models.default_list),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=projects.models.default_list),
        ),
    ]
