# Generated by Django 4.2.16 on 2025-10-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_add_department_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectattachment",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the attachment", null=True
            ),
        ),
    ]
