# Generated by Django 4.2.16 on 2025-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_update_attachment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='moyen', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planification', 'Planification'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('en_retard', 'En retard'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planification', max_length=20),
        ),
    ]
