# Generated by Django 4.2.7 on 2025-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App'), ('desktop_app', 'Desktop App'), ('data_analysis', 'Data Analysis'), ('research', 'Research'), ('marketing', 'Marketing'), ('ai_ml', 'AI/ML'), ('devops', 'DevOps'), ('gaming', 'Gaming'), ('iot', 'IoT'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
