# Generated by Django 4.2.7 on 2025-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('Annulé', 'Annulé'), ('En attente', 'En attente'), ('En retard', 'En retard'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='planning', max_length=20),
        ),
    ]
