# Generated by Django 4.2.16 on 2025-10-26 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("comptabilite", "Comptabilité"),
                            ("finance", "Finance"),
                            ("service_clients", "Service clients"),
                            ("risque_clients", "Risque clients"),
                            ("service_generaux", "Service généraux"),
                            ("controle_gestion", "Contrôle de gestion"),
                            ("juridique", "Juridique"),
                            ("evenementiel", "Événementiel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Permission",
                "verbose_name_plural": "Department Permissions",
                "db_table": "department_permissions",
                "unique_together": {("user", "department")},
            },
        ),
    ]
