# Generated by Django 4.2.7 on 2025-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filiale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
