# Generated by Django 4.2.7 on 2025-09-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_user_roles'),
        ('authentication', '0006_user_roles'),
    ]

    operations = [
    ]
