# Generated by Django 4.2.7 on 2025-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merge_0006_add_user_roles_0006_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('users', 'Utilisateurs'), ('projects', 'Projets'), ('tasks', 'Tâches'), ('teams', 'Équipes'), ('calendar', 'Calendrier'), ('reports', 'Rapports'), ('settings', 'Paramètres'), ('finance', 'Finance'), ('hr', 'Ressources Humaines'), ('inventory', 'Inventaire'), ('sales', 'Ventes'), ('marketing', 'Marketing')], default='users', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('tester', 'Tester'), ('user', 'User'), ('PROJECT_MANAGER', 'Project Manager'), ('PROJECT_USER', 'Project User')], default='user', max_length=20),
        ),
    ]
