# Generated by Django 4.2.7 on 2025-10-05 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du template')),
                ('subject_template', models.CharField(max_length=200, verbose_name='Template du sujet')),
                ('body_template', models.TextField(verbose_name='Template du corps')),
                ('notification_type', models.CharField(choices=[('project_created', 'Projet créé'), ('project_updated', 'Projet mis à jour'), ('project_deleted', 'Projet supprimé'), ('task_assigned', 'Tâche assignée'), ('task_completed', 'Tâche terminée'), ('deadline_reminder', "Rappel d'échéance"), ('user_registered', 'Utilisateur enregistré'), ('system_alert', 'Alerte système')], max_length=50, verbose_name='Type de notification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Template Email',
                'verbose_name_plural': 'Templates Email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('project_created', 'Projet créé'), ('project_updated', 'Projet mis à jour'), ('project_deleted', 'Projet supprimé'), ('task_assigned', 'Tâche assignée'), ('task_completed', 'Tâche terminée'), ('deadline_reminder', "Rappel d'échéance"), ('user_registered', 'Utilisateur enregistré'), ('system_alert', 'Alerte système')], max_length=50, verbose_name='Type de notification')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('delivered', 'Livré')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet lié')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name="Type d'objet lié")),
                ('send_immediately', models.BooleanField(default=True, verbose_name='Envoyer immédiatement')),
                ('scheduled_send_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'envoi programmée")),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Nombre maximum de tentatives')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification Email',
                'verbose_name_plural': 'Notifications Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.emailnotification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'Log Email',
                'verbose_name_plural': 'Logs Email',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_3f0cef_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_b41f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['priority', 'status'], name='notificatio_priorit_53c109_idx'),
        ),
    ]
