# Generated by Django 4.2.7 on 2025-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'objet lié"),
        ),
    ]
